// Auto-generated by `npx boneyard-js scan` — do not edit
import { registerBones } from 'boneyard-js/native'

import _product_detail from './product-detail.bones.json'

registerBones({
  "product-detail": _product_detail,
})
